### ISSUE TITLE
fails with "ValueError: could not convert string to float:"

### ISSUE THREAD

**Issue by rkoe** [The-Compiler/journalwatch#25]
## Bug description

Since a recent Linux-System-update, journalwatch does not work anymore; instead it fails with:

```
$ journalwatch print
Traceback (most recent call last):
  File "/nix/store/4my8gfpc9nl8pq1q9rf6kwa7h0n307xv-python3.9-journalwatch-1.1.0/bin/.journalwatch-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/4my8gfpc9nl8pq1q9rf6kwa7h0n307xv-python3.9-journalwatch-1.1.0/lib/python3.9/site-packages/journalwatch.py", line 505, in main
    run()
  File "/nix/store/4my8gfpc9nl8pq1q9rf6kwa7h0n307xv-python3.9-journalwatch-1.1.0/lib/python3.9/site-packages/journalwatch.py", line 488, in run
    since = parse_since()
  File "/nix/store/4my8gfpc9nl8pq1q9rf6kwa7h0n307xv-python3.9-journalwatch-1.1.0/lib/python3.9/site-packages/journalwatch.py", line 451, in parse_since
    since = datetime.fromtimestamp(float(f.read()))
ValueError: could not convert string to float: ''
```

## System information

- OS: Linux, NixOS 21.11

**Comment by rkoe** [comment]
Looks like this is caused by something crashing `~/.local/share/journalwatch/time`
Solution: Run `journalwatch --since all print` once; this will restore the file, so following calls work again.

**Comment by The-Compiler** [comment]
Glad you got it sorted out! No idea how it happened though - apparently, the file was empty in your case, but all journalwatch does is:

https://github.com/The-Compiler/journalwatch/blob/363725ac4b8aa841d87654fa8a63403a59ad1275/journalwatch.py#L470-L473

I added a better error message for that case to 363725ac4b8aa841d87654fa8a63403a59ad1275 now.
